author: 若离QQ：2909998156
# 调试模式，用于寻找错误出现的坐标，默认为false
# 特别提示：调试完成后请记得将debug改为false
# 特别提示：调试完成后请记得将debug改为false
# 特别提示：调试完成后请记得将debug改为false
debug: false
# 推送方式：0：邮件推送；1：qmsg推送；2：pushplus推送
sendType: 0
# 当且仅当sendType为0时有用，邮箱API的地址
emailApiUrl: 'https://api.ruoli.cc/sendMail'
# 当且仅当sendType为1时有用，qmsg的Key（如需使用请自行更改）
myQmsgKey: ''



#用户组配置
##################################################
# 温馨提示：请仔细注意每个模板是属于哪个任务类型的配置！##
##################################################
users:
  # 第二个用户配置
  # 以下配置为信息收集
  # 这里默认仅适配宜宾学院，其他学校自行修改
  - user:
        # 任务类型（收集：0、签到：1、查寝2）
        type: 0
        # 学校名称
        schoolName: '宜宾学院'
        # 账号
        username: '181102009'
        # 密码
        password: '15982305676byqhy'
        # 定位位置信息
        address: '四川省宜宾市大学路三段5号'
        #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码，当sendType为2时代表接收消息的pushplus token
        sendKey: '1471927275@qq.com'
        # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
        # 经纬度信息
        lon: 104.6191824
        #经纬度信息
        lat: 28.800613
        # 是否检查表单的标题（1代表检查，0代表不检查）
        checkTitle: 1
        #代理ip信息（格式为：网络协议://ip地址:端口   如：http://127.0.0.1:7890）
        proxy:
        # 表单信息
        forms:
            - form:
                  title: 今日具体所在地
                  value: 四川省/宜宾市/翠屏区
            - form:
                  title: 是否在校
                  value: 是
            - form:
                  title: 上午体温
                  value: '36.2'
            - form:
                  title: 下午体温
                  value: '36.2'
            - form:
                  title: 晚上体温
                  value: '36.5'
            - form:
                  title: 身体状况
                  value: 身体健康
            - form:
                  title: 是否今日返校？
                  value: 否
